name: Publish Docs to gh-pages Branch
on:
  push:
    branches: [main]
    paths: # only publish new docs upon changes to these files:
      - "**.py*"
      - "**.md*"
      - "**.rst"
      - .readthedocs.yaml

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: setup python, poetry, and dev dependencies
        uses: ./.github/actions/setup-python

      - name: Sphinx build
        run: poetry run sphinx-build -b html -d docs/_build/doctrees docs docs/_build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
